[package]
name = "goffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "goffi"
crate-type = [ "rlib" ]

[dependencies]
fama-common = { path = "../../common" }
libc = "0.2"

[build-dependencies]
cc = "1.0"
