[package]
name = "kotlin-formatter"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "kotlin_formatter"
crate-type = ["rlib"]

[dependencies]
fama-common = { path = "../fama-common" }
tree-sitter = "0.22"
tree-sitter-kotlin = "0.3"
