[package]
name = "rustfmt"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "rustfmt"
crate-type = [ "rlib" ]

[dependencies]
fama-common = { path = "../../common" }
rust-format = "0.3"
